---
- name: Install packages 
  ansible.builtin.package:
    name: "python3-pip"
    state: present

- name: Install python packages for docker
  pip:
    name:
      - docker
      - docker-compose

- name: Create a directory for compose
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0777'

- name: Configure docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Restart docker #https://stackoverflow.com/questions/38087027/docker-compose-stuck-downloading-or-pulling-fs-layer
  service:
    name: docker
    state: restarted
  changed_when: false

- name: Docker-Compose UP
  docker_compose:
    project_src: "{{ docker_compose_dir }}"
  tags: service_deploy
