---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: dhcp-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: dhcp
        ipam_config:
          - subnet: "172.24.0.0/24"
            gateway: "172.24.0.1"
    networks:
      - name: dhcp
    groups:
      - dhcp
provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
  env:
    ANSIBLE_VERBOSITY: 2
    ANSIBLE_ROLES_PATH: "../../roles"
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
